### ISSUE TITLE
plugin fails to load due to missing zeroconf module

### ISSUE THREAD

**Issue by dduff617** [FlyingDiver/Indigo-Lutron-Leap#1]
lutron leap plugin was showing with a red dot in my plugins menu.   attempting to reload produced an error complaining about missing zeroconf module. 

running 'pip3 install zeroconf' seemed to fix, after that i was able to do a reload of the plugin from within Indigo, then was greeted by a configuration dialog.

**Comment by FlyingDiver** [comment]
Sounds about right.  I need to update the docs.

Please do let me know what devices you're able to test it with.  If any of them do something wrong/unexpected, open a new issue and post the logs.  I'll leave this open until I get a change to update the docs.
