### ISSUE TITLE
suggested additions to README.md

### ISSUE THREAD

**Issue by dduff617** [FlyingDiver/Indigo-Lutron-Leap#2]
it would be useful to have some info about the following topics in the README.md: 

**migration from / co-existence with "Lutron RRA2/Caséta" plugin**

do you need to delete existing devices and disable the old plugin before setting up Lutron Leap plugin?   will enabling the new one delete or mess up your old devices/settings or will it allow you revert? 

under what circumstances might someone using Lutron RRA2/Caséta plugin want to migrate to LEAP - i.e., what are the potential advantages of LEAP?   is LEAP newer and/or better (i presume yes to both)?     i can read lutron's story about LEAP [here](https://support.lutron.com/us/en/product/radiora3/article/networking/Lutron-s-LEAP-API-Integration-Protocol), but am curious mainly how those benefits manifest to a Indigo plugin user - i tried to navigate Lutron's descriptions of their various protocols and products but very quickly got buried in the complexity.  

in my particular case, all of my devices are already setup and working with the old plugin, with the only exception being that i can't seem to get battery level or low-battery warnings for my battery-powered devices (shades/remotes).   so i am curious whether LEAP protocol might somehow help with that issue...

**Comment by dduff617** [comment]
a few other questions about LEAP while i'm at it:   

is LEAP only used between the plugin and the Lutron Smart Hub Pro?    or does using LEAP plugin somehow also change the protocol that's used to communicate between the LSHP and lutron devices in my network?

related question:  does using LEAP change any of the basic characteristics/constraints of my Lutron system?   for example, i believe that i read somewhere that the _max device limit_ is fairly low for some types of Lutron systems such as "Caseta" (possibly including my own, although to be honest, i'm not certain).   this is not a huge concern for me at the moment, but could influence future buying decisions...   i also read that LEAP adds some _comms security features_ that older Lutron protocols lacked - does this actually represent improved security on my network of home devices?

**Comment by FlyingDiver** [comment]
> do you need to delete existing devices and disable the old plugin before setting up Lutron Leap plugin? will enabling the new one delete or mess up your old devices/settings or will it allow you revert?

You can run them in parallel.  The hub device and the indigo devices representing the Lutron HW will be duplicated for the new plugin.  Not all devices in the original plugin exist in the Leap plugin.  Some things, like Pico keypads, don't have a device in Indigo, but do create events that can be triggered on.

> under what circumstances might someone using Lutron RRA2/Caséta plugin want to migrate to LEAP - i.e., what are the potential advantages of LEAP? is LEAP newer and/or better (i presume yes to both)? i can read lutron's story about LEAP [here](https://support.lutron.com/us/en/product/radiora3/article/networking/Lutron-s-LEAP-API-Integration-Protocol), but am curious mainly how those benefits manifest to a Indigo plugin user - i tried to navigate Lutron's descriptions of their various protocols and products but very quickly got buried in the complexity.

I can't think of a use case for switching right now, but there might be in the future if new functionality is introduced.  The primary case is if there's a Hardware change.  RRa2 users with a bad repeater are being forced to switch to an RRa3 repeater because there's no stock of the RRa2 units left.  They've been discontinued.

>in my particular case, all of my devices are already setup and working with the old plugin, with the only exception being that i can't seem to get battery level or low-battery warnings for my battery-powered devices (shades/remotes). so i am curious whether LEAP protocol might somehow help with that issue...

Maybe.  I'd have to see the data returned by the devices to see if there's any battery level info in them.  

>is LEAP only used between the plugin and the Lutron Smart Hub Pro? or does using LEAP plugin somehow also change the protocol that's used to communicate between the LSHP and Lutron devices in my network?

AFAIK, it's specific to communication between the repeater or hub and client devices.  Like mobile apps.  Comms between the repeater/hub and the devices is some proprietary RF protocol.

>related question: does using LEAP change any of the basic characteristics/constraints of my Lutron system? for example, i believe that i read somewhere that the max device limit is fairly low for some types of Lutron systems such as "Caseta" (possibly including my own, although to be honest, i'm not certain). this is not a huge concern for me at the moment, but could influence future buying decisions... i also read that LEAP adds some comms security features that older Lutron protocols lacked - does this actually represent improved security on my network of home devices?

No changes to system limits.  It's just a comm protocol, replacing the Telnet protocol used in the previous plugin.  And yes, it's more secure than Telnet.  But that would only be an issue if your network is not secure.

**Comment by FlyingDiver** [comment]
One other important caveat - the original plugin is based on the Telnet protocol which Lutron published for anyone to use.  The LEAP protocol is NOT published, and not publicly available.  We've been trying to get official access to that protocol for almost 2 years now, and Lutron keeps dragging their feet.  So the new LEAP protocol is based on the reverse-engineered protocol and library that HomeAssistant uses.

See https://github.com/gurumitts/pylutron-caseta

**Comment by dduff617** [comment]
thanks for excellent clarifications!

**Comment by FlyingDiver** [comment]
Readme updated.    Will appear in next release.
